#!/bin/bash
mkdir /var/lib/grafana/dashboards
curl https://raw.githubusercontent.com/fluent/m3-workshop-fluentcon/master/config/grafana/dashboards/Prometheus_2_0_Stats.json >> /var/lib/grafana/dashboards/Prometheus_2_0_Stats.json
curl https://raw.githubusercontent.com/fluent/m3-workshop-fluentcon/master/config/grafana/dashboards/Prometheus_Stats.json >> /var/lib/grafana/dashboards/Prometheus_Stats.json
curl https://raw.githubusercontent.com/fluent/m3-workshop-fluentcon/master/config/grafana/dashboards/node-exporter-full_rev23.json >> /var/lib/grafana/dashboards/node-exporter-full_rev23.json
curl https://raw.githubusercontent.com/fluent/m3-workshop-fluentcon/master/config/grafana/provisioning/dashboards/prometheus_ds.yml >> /etc/grafana/provisioning/dashboards/prometheus_ds.yml
curl https://raw.githubusercontent.com/fluent/m3-workshop-fluentcon/master/config/grafana/provisioning/datasources/datasources.yml >> /etc/grafana/provisioning/datasources/datasources.yml

grafana-server stop
grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=docker cfg:default.log.mode=console cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
